"""
create_pylock.py — Unified dependency synchronization for VAHN backend.

Synchronizes all 3 dependency lock manifests:
1. backend/uv.lock (Astral uv lockfile)
2. backend/requirements.txt (Standard pip/fallback manifest)
3. backend/pylock.toml (PEP 751 compatible lockfile)
"""

import os
import shutil
import subprocess
import sys

BACKEND_DIR = os.path.join(os.path.dirname(__file__), "backend")
LOCK_FILE = os.path.join(BACKEND_DIR, "pylock.toml")
UV_LOCK_FILE = os.path.join(BACKEND_DIR, "uv.lock")
REQ_FILE = os.path.join(BACKEND_DIR, "requirements.txt")


def find_uv_binary():
    # 1. System PATH
    uv_path = shutil.which("uv")
    if uv_path:
        return uv_path
    # 2. Virtual environment in backend
    venv_uv = os.path.join(BACKEND_DIR, ".venv", "Scripts", "uv.exe")
    if os.path.isfile(venv_uv):
        return venv_uv
    venv_uv_posix = os.path.join(BACKEND_DIR, ".venv", "bin", "uv")
    if os.path.isfile(venv_uv_posix):
        return venv_uv_posix
    return None


def sync_uv_lock(uv_bin):
    print("[1/3] Synchronizing uv.lock...")
    try:
        subprocess.run([uv_bin, "lock"], cwd=BACKEND_DIR, check=True)
        print(f"[OK] uv.lock updated -> {UV_LOCK_FILE}")
    except Exception as e:
        print(f"[WARN] Warning: Could not run uv lock: {e}")


def sync_requirements_txt(uv_bin):
    print("[2/3] Exporting requirements.txt...")
    try:
        subprocess.run(
            [uv_bin, "export", "--no-dev", "--no-hashes", "-o", REQ_FILE],
            cwd=BACKEND_DIR,
            check=True,
            capture_output=True,
            text=True
        )
        print(f"[OK] requirements.txt updated -> {REQ_FILE}")
    except Exception as e:
        print(f"[WARN] Warning: Could not export requirements.txt via uv: {e}")


def get_installed_packages():
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"],
        capture_output=True, text=True, check=True
    )
    packages = []
    for line in result.stdout.strip().splitlines():
        if "==" in line and not line.startswith("#"):
            name, version = line.split("==", 1)
            packages.append({"name": name.strip(), "version": version.strip()})
    return packages


def write_pylock_toml(packages):
    print("[3/3] Writing pylock.toml...")
    package_blocks = []
    for pkg in packages:
        block = f'[[packages]]\nname = "{pkg["name"]}"\nversion = "{pkg["version"]}"'
        package_blocks.append(block)

    content = (
        '# pylock.toml — Backend dependency lock file\n'
        '# Generated by create_pylock.py (PEP 751 compatible)\n'
        f'# Python: {sys.version.split()[0]}\n\n'
        '[metadata]\n'
        'lock-version = "1.0"\n'
        f'requires-python = ">={sys.version_info.major}.{sys.version_info.minor}"\n\n'
    ) + '\n\n'.join(package_blocks) + '\n'

    with open(LOCK_FILE, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"[OK] pylock.toml written -> {LOCK_FILE} ({len(packages)} packages locked)")


if __name__ == "__main__":
    uv_bin = find_uv_binary()
    if uv_bin:
        print(f"Found Astral uv at: {uv_bin}")
        sync_uv_lock(uv_bin)
        sync_requirements_txt(uv_bin)
    else:
        print("Astral uv not found in PATH or venv; skipping uv lock & export")

    packages = get_installed_packages()
    write_pylock_toml(packages)
    print("\nAll dependency manifests synchronized successfully!")
