"""
create_pylock.py — Generates pylock.toml for the backend virtualenv.

Uses pip's PEP 751 export if available (Python 3.13+ / pip 24.1+),
otherwise falls back to generating a compatible TOML manually from pip freeze.
"""

import subprocess
import sys
import importlib.metadata
import re
import os
try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:
    tomllib = None

LOCK_FILE = os.path.join(os.path.dirname(__file__), "backend", "pylock.toml")


def get_installed_packages():
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"],
        capture_output=True, text=True, check=True
    )
    packages = []
    for line in result.stdout.strip().splitlines():
        if "==" in line and not line.startswith("#"):
            name, version = line.split("==", 1)
            packages.append({"name": name.strip(), "version": version.strip()})
    return packages


def write_pylock_toml(packages):
    lines = [
        '# pylock.toml — Backend dependency lock file',
        '# Generated by create_pylock.py (PEP 751 compatible)',
        f'# Python: {sys.version}',
        '',
        '[metadata]',
        'lock-version = "1.0"',
        f'requires-python = ">={sys.version_info.major}.{sys.version_info.minor}"',
        '',
        '[[packages]]',
    ]

    package_blocks = []
    for pkg in packages:
        block = f'[[packages]]\nname = "{pkg["name"]}"\nversion = "{pkg["version"]}"'
        package_blocks.append(block)

    content = (
        '# pylock.toml — Backend dependency lock file\n'
        '# Generated by create_pylock.py (PEP 751 compatible)\n'
        f'# Python: {sys.version.split()[0]}\n\n'
        '[metadata]\n'
        'lock-version = "1.0"\n'
        f'requires-python = ">={sys.version_info.major}.{sys.version_info.minor}"\n\n'
    ) + '\n\n'.join(package_blocks) + '\n'

    with open(LOCK_FILE, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"[OK] pylock.toml written -> {LOCK_FILE}")
    print(f"  Locked {len(packages)} packages")


if __name__ == "__main__":
    try:
        # Try pip's native PEP 751 export first (pip >= 24.1 / Python 3.13+)
        result = subprocess.run(
            [sys.executable, "-m", "pip", "export", "--format=pep751", f"--output={LOCK_FILE}"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(f"[OK] pylock.toml written via pip PEP 751 export -> {LOCK_FILE}")
            sys.exit(0)
    except Exception:
        pass

    # Fallback: generate manually from pip freeze
    packages = get_installed_packages()
    write_pylock_toml(packages)
