name: vahn-vpn-stack

services:
  vpn:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: vahn-vpn
    restart: always
    environment:
      - WG_HOST=65.2.203.191
      - PASSWORD_HASH=$$2a$$12$$b18U7NWiiEq1.48InXu34.mqaSVg2IA3KnsnnU/Cht4CnN1io83Ay
      - WG_PORT=51820
      - PORT=51821
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=10.8.0.1, 1.1.1.1
      - WG_ALLOWED_IPS=10.8.0.0/24
    volumes:
      - vahn_wireguard_data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
    networks:
      - vahn-network

  dns:
    image: coredns/coredns:1.11.1
    container_name: vahn-dns
    restart: always
    user: "0:0"
    network_mode: "service:vpn"
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile:ro
    command: -conf /etc/coredns/Corefile
    depends_on:
      - vpn

  proxy:
    image: alpine/socat:latest
    container_name: vahn-vpn-proxy
    restart: always
    network_mode: "service:vpn"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "socat -d -d TCP4-LISTEN:80,fork,reuseaddr TCP4:vahn-caddy-prod:80 &
       exec socat -d -d TCP4-LISTEN:443,fork,reuseaddr TCP4:vahn-caddy-prod:443"
    depends_on:
      - vpn

volumes:
  vahn_wireguard_data:
    external: true
    name: vahn_wireguard_data

networks:
  vahn-network:
    external: true
    name: vahn_prod_network
