"""add_fit_kit_type_activity_to_products

Revision ID: c98a31e84012
Revises: b57c4b2367d9
Create Date: 2026-07-21 23:12:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98a31e84012'
down_revision: Union[str, None] = 'b57c4b2367d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('fit', sa.String(), nullable=True))
    op.add_column('products', sa.Column('kit_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('activity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'activity')
    op.drop_column('products', 'kit_type')
    op.drop_column('products', 'fit')
    # ### end Alembic commands ###
